Repository SOACodeRoom/Summer-Hacks, pull requests merged in 2021-04, with the labels that each got.

#1 first version of website added
  css/bootstrap.min.css
  css/style.css
  img/logo.png
  img/logo.svg
  img/pure-virtual-sticker.svg
  img/title-scrolling.png
  index.html
  js/script.js
Labels: enhancement

#3 Audio Added to Background
  index.html
Labels: enhancement

#4 The audio file for the background music.
  audio/tech-house.mp3
Labels: enhancement

#11 Added the About & PS Section
  css/style.css
  index.html
  js/app.js
  js/particles.js
Labels: enhancement, merged

#12 Theme Webpage Added
  theme.html
Labels: enhancement

#14 Theme Section added
  css/themes.css
  js/themes.js
  theme.html
Labels: enhancement

#15 Theme
  css/themes.css
  js/themes.js
  theme.html
Labels: enhancement, merged

#17 Add faq template
  faqs.html
Labels: enhancement

#18 404 Page Added
  404.html
Labels: enhancement

#25 Add codeofconduct
  codeofconduct.html
Labels: enhancement

#28 -add code of conduct with links & grammatically
  README.md
  codeofconduct.html
  index.html
Labels: documentation, enhancement
